# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: login-to-server
        uses: cross-the-world/ssh-pipeline@v1.2.0
        with:
          host: bfcc.dev
          port: 22222
          user: root
          key: ${{ secrets.BFCC_SERVER_KEY }}
          script: ./publish.sh

#       - name: echo
#         env:
#           GITHUB_CONTEXT: ${{ toJSON(github) }}
#           RUN_ID: ${{github.run_id}}
#           ACTION_URL: ${{github.run_id}} + ${{github.repository.url}}/runs/2438059681?check_suite_focus=true
#         run: echo $ACTION_URL

  
      - name: feishu bot
        uses: wangsijie/feishu-bot@v1
        with:
          version: 2
          uuid: e3fdc3fd-b741-483f-b655-1c71e0155652
          text: nginx 更新成功 @胡东阳 可以刷新 CDN 啦
  
